Added eslint, prettier, updated expo-cli and extension reccommendations for vscode
KuzniaCo/chemistry-app pull request #13
Opened 2022-04-14 20:16 UTC by hubcio2115

Relates to #6 and my [comment](https://github.com/KuzniaCo/chemistry-app/issues/6#issuecomment-1094106850)

2022-04-16 09:27 UTC, bartlomiejmont requested changes

2022-04-16 09:27 UTC, bartlomiejmont commented on package.json
> +    "expo-cli": "^5.3.1",
expo-cli should be dev-dependency

2022-04-16 09:27 UTC, bartlomiejmont commented on package.json
> +    "prettier": "^2.6.2",
same here, we don't need It on production so it should be a dev-dep

2022-04-16 09:40 UTC, bartlomiejmont commented
Great Idea to add some consistency to our code. Maybe it's a great opportunity to also configure [Husky](https://typicode.github.io/husky/#/)

2022-04-22 17:08 UTC, hubcio2115 commented on package.json
> +    "expo-cli": "^5.3.1",
yes it should, now it will be

2022-04-22 17:11 UTC, hubcio2115 commented on package.json
> +    "prettier": "^2.6.2",
but it is

2022-04-22 17:59 UTC, hubcio2115 commented
> Great Idea to add some consistency to our code. Maybe it's a great opportunity to also configure [Husky](https://typicode.github.io/husky/#/)

What would that add to the project? We already have recommended extensions for vscode that do `prettier --write` automatically. Maybe blocking ability to commit changes with linting errors/warnings?

We would check that anyway with GitHub Actions so I don't see any advantage of that.

2022-04-25 18:16 UTC, BartoszBrodowski approved these changes

2022-04-25 19:29 UTC, bartlomiejmont commented
> 



> > Great Idea to add some consistency to our code. Maybe it's a great opportunity to also configure [Husky](https://typicode.github.io/husky/#/)
> 
> What would that add to the project? We already have recommended extensions for vscode that do `prettier --write` automatically. 

>Maybe blocking ability to commit changes with linting errors/warnings?

That's basically what husky does 😄. 

> We would check that anyway with GitHub Actions so I don't see any advantage of that.

It's always better to check that before running the pipeline to avoid wasting resources.

Also, we could maintain good commit message quality.

2022-04-25 19:36 UTC, bartlomiejmont approved these changes
Looks good. Moved Husky implementation to another ticket #34 😉

2022-04-25 19:54 UTC, hubcio2115 commented
> Looks good. Moved Husky implementation to another ticket #34 😉

Than that means I should read into Husky. Also we could introduce [Volta](https://volta.sh/) so that everyone can be on the same version of Node. But with this we may be comming into too much tooling teritory.

2022-04-25 19:54 UTC, merged

2022-04-26 07:05 UTC, bartlomiejmont commented
> 



> > Looks good. Moved Husky implementation to another ticket #34 😉
> 
> Than that means I should read into Husky. Also we could introduce [Volta](https://volta.sh/) so that everyone can be on the same version of Node. But with this we may be comming into too much tooling teritory.

Never heard of that, I am using [NVM ](https://github.com/nvm-sh/nvm#intro) but it looks very similar

2022-04-26 13:13 UTC, hubcio2115 commented
I've been using NVM until recently, but it wasn't working with me in JetBrains IDEs. So I changed to Volta. IMO it is more intuitive and has things like remembering specific node, npm and yarn versions depending on where you are in a file system.

Also you can specify the versions in package.json so Volta can pick it up and set them for you.

Don't know if NVM has similar features.