Login view
KuzniaCo/chemistry-app pull request #23
Opened 2022-04-21 18:40 UTC by BartoszBrodowski

Created Login view. Added expo-linear-gradient to make gradient effect on the background. I didn't add much types in the component as I'm not certain they're needed/proper.

Icons that I've used come from FontAwesome5 and AntDesign. They both come with expo-vector-icons that were already included.

You can also check whether the styles fit good practises. I used margins to space out the components, however it doesn't seem like it breaks things in react-native. You can correct me on that one and maybe give a tip about fixing it and I'll do my best to make appropriate changes.

2022-04-22 19:53 UTC, hubcio2115 commented on components/Login.tsx
> +// expo-linear-gradient
This is not needed since we can see changed made in `package.json` and `yarn.lock`. But the intention was good.

2022-04-22 19:54 UTC, hubcio2115 commented on components/Login.tsx
> +// React-native nie ma wbudowanego gradientu.
Same thing here as above

2022-04-22 19:57 UTC, hubcio2115 commented on components/Login.tsx
> +                >
Don't use `React.FC`. [Here](https://github.com/facebook/create-react-app/pull/8177) is the explanation why.

When typing a component you should add type just for `props` and maybe `JSX.Element` for a return type of the component just to be sure.

2022-04-22 19:59 UTC, hubcio2115 commented on components/Login.tsx
> +                        <Text>logo/nazwa</Text>
Don't write shortened names for variables. Name them with full words for example `passwordIcon`. It doesn't matter even if it's 20 characters long and it gives code good looks :)

2022-04-22 20:08 UTC, hubcio2115 requested changes
Reply to my comments.

2022-04-22 22:21 UTC, BartoszBrodowski commented on components/Login.tsx
> +// expo-linear-gradient
Deleted the comments as I thought it through and I think they're not necessary. Next time I'll remember to write comments in English = )

2022-04-22 22:22 UTC, BartoszBrodowski commented on components/Login.tsx
> +// React-native nie ma wbudowanego gradientu.
Deleted as well.

2022-04-22 22:24 UTC, BartoszBrodowski commented on components/Login.tsx
> +                >
I've changed it from React.FC to JSX.Element but I've put it in a slightly different place. I'm not sure whether this is the proper syntax as I don't have any experience with TypeScript, however when I checked the app after the change it worked just fine.

2022-04-22 22:27 UTC, BartoszBrodowski commented on components/Login.tsx
> +                        <Text>logo/nazwa</Text>
Changed the names. Thought they would be too long but couldn't make up descriptive names for some of them so I decided to use abbreviations. Now they're slightly longer and better looking.

2022-04-22 22:31 UTC, BartoszBrodowski commented
Have done the changes however not all of the points are labeled as "Outdated" due to the fact that I've done many things at once. Next time I'll remember to make less changes at one time so all the comments get labeled as "Outdated" when I fix the problems.

2022-04-23 06:52 UTC, hubcio2115 approved these changes

2022-04-25 08:35 UTC, greenvar48 approved these changes

2022-04-25 10:17 UTC, merged