31 main view
KuzniaCo/chemistry-app pull request #50
Opened 2022-05-15 17:39 UTC by BartoszBrodowski

Adding main view. There's no callendar included as I was told not to add it yet. 
On Android looks like this:
![MainView](https://user-images.githubusercontent.com/94301235/168486319-28e27d46-4d20-42ae-8e27-da058431bcf3.jpg)

2022-05-16 10:20 UTC, komolcia approved these changes
Everything looks fine. No changes required.

2022-05-17 14:58 UTC, kacperkruger requested changes
I think numbers in rectangles should be bigger and white like on figma

2022-05-17 14:58 UTC, kacperkruger commented on src/ui/components/MainView.js
> +					)}></Animated.FlatList>
You should use here self closing tag

2022-05-17 14:58 UTC, kacperkruger commented on src/ui/components/MainView.js
> +			<StatusBar backgroundColor={'transparent'} translucent={false} />
I think status bar should be handled in app.js, so the status bar will be the same for every component

2022-05-22 16:37 UTC, kacperkruger reviewed
👍👍

2022-05-22 16:38 UTC, kacperkruger approved these changes

2022-05-29 17:14 UTC, merged